### ISSUE TITLE
hvac_action not updated sometimes

### ISSUE THREAD

**Issue by ra-kal** [MislavMandaric/home-assistant-vaillant-vsmart#206]
Component version v0.6.3
HA Version 2022.11.4

Problem description:
The hvac_action sometimes does not update. The boiler is heating, the current_temperature is increasing, but hvac_action remains idle. I've confirmed the boiler heating operation in eRelax application.

Unfortunately there is no sign of any error in the log.

**Comment by MislavMandaric** [comment]
Hey @ra-kal.

First of all, thank you for using the integration 😄 

Can you please check what is the current temperature that's reported by the integration and what is the desired temperature? The integration currently doesn't expose "boiler is working" data. Instead, it only shows "heating" action if the current temperature is lower than desired temperature.

I have plans on exposing the real "boiler is working" data point, with hvac_action using that information to show if boiler is heating or not, but right now that is not the case.

**Comment by ra-kal** [comment]
Hi, thanks for this integration!

Yes, it looks like the "heating" is only reported when the current temperature is below set temperature.

I have a VUI boiler. Would it be also possible set hot water temperature? Maybe battery level, etc.? It is not that necessary, just asking if it is possible. Or what everything can exposed?

**Comment by MislavMandaric** [comment]
Quick update regarding the original issue reported.

With awesome contribution from @vneno in #230, this issue should now be fixed. Please update to the latest version.

Regarding the other suggestions - HWB temperature is also released, battery as well. There are many more data points that can be exposed and I'm going to work on exposing them. But keep in mind that this is a hobby project that I'm working on when I have some spare time, so the pace is somewhat slowish.
