### ISSUE TITLE
Add electricity consumption

### ISSUE THREAD

**Issue by stShark** [MislavMandaric/home-assistant-vaillant-vsmart#210]
hi, would it be possible to supplement the electricity consumption sensor?
This data is in the application on the phone.
well thank you

**Comment by MislavMandaric** [comment]
Hi @stShark.

This is something @Przemko92 started working on in the API library repository [here](https://github.com/MislavMandaric/vaillant-netatmo-api/pull/88).

After that work is done, we'll work on implementing it in the integration as well.

**Comment by Przemko92** [comment]
Hi @stShark 

As @MislavMandaric  mentiuoned we are working on that. It will be possible to get gas and electricity consumption.

**Comment by stShark** [comment]
Hi @Przemko92 @MislavMandaric,

well thank you. I believe that this modification will be beneficial to many home assistant users. once again thank you very much

**Comment by lozo2010** [comment]
Hi. Is there any news about the integration of consumption?

**Comment by Przemko92** [comment]
Hi. I'm waiting till my changes were released. After release i can implement energy consumption in the ha addon.

**Comment by MislavMandaric** [comment]
Well this is embarrassing 😓 

I was sure I published your changes, but apparently I did not. I just approved the release and it's published on PyPI [just now](https://github.com/MislavMandaric/vaillant-netatmo-api/releases/tag/v0.11.0).

I'm really sorry for missing this. I'm decluttering my Github notifications and setting up better notifications for release approvals, to avoid this happening again.

**Comment by dlozoya** [comment]
Do not worry. I see that it is published. Now will be insert the @Przemko92 changes in this repository right?

**Comment by lozo2010** [comment]
Do not worry. I see that it is published. Now will be insert the @Przemko92 changes in this repository right?

**Comment by Przemko92** [comment]
Try to install my changes. https://github.com/Przemko92/home-assistant-vaillant-vsmart

**Comment by Nimayer** [comment]
Hi @MislavMandaric,
Could you add support for electricity/gas consumption, since it’s now supported in vaillant-netatmo-api?

**Comment by stShark** [comment]
hello, the sensor for measuring consumption has stopped working in the integration: sensor.elec_heating. reports as unavailable

**Comment by MislavMandaric** [comment]
Hey everyone.

I managed to release a new dev pre-release with energy sensors. Big thanks and shout-out to @Przemko92 and @albaintor for helping out with this ❤️ 

I'll publish a final release after testing it for a bit in my setup. Feel free to install it too if you'd like to test it out as well.
