### ISSUE TITLE
Expose boiler domestic hot water temperature

### ISSUE THREAD

**Issue by superbunika** [MislavMandaric/home-assistant-vaillant-vsmart#217]
Expose boiler domestic hot water temperature so it can be used in automations.

Great usecase for this would be antilegionella automation. For example, when you're away from home for a longer time (typically a week or more), you could set hot water temperature to +60 C for an hour weekly and then revert back to default value. Very usable for people with water tanks.

**Comment by MislavMandaric** [comment]
Hey @superbunika.

This should be available in the next version, with #232 being merged.

**Comment by vneno** [comment]
Great work, i aldready did it at last night but as watherheater entity. So as operation mode you can choose between "always on" or "based on schedule".  So, to be able to determine the dhw_always_on attr, it seems to be necessary to imitate mobile app api call to read it. I did not find any sutable attr in response from /api/getthermostatsdata.  BTW API path /api/getthermostatsdata, /api/getthermostatsdata seems to be undocumented or at least I was not able to find it. :) Soon I will propose my solution for waterheater entity.

**Comment by MislavMandaric** [comment]
Nice, let's see how it looks.

With the integration I mostly wanted to imitate the native Vaillant app and in there water temperature is just a setting.

But if we can combine HWB switch and DHW config into a nice WaterHeater entity, I'd very much like so.

**Comment by vneno** [comment]
I think that the HWB switch should remain the same as it is now. 
In DHW component will see if the boiler is heating domestic water (ON/OFF states), set target temperature of hot water and set operation mode (always on/ based on schedule)
