### ISSUE TITLE
Hot water boost preset for Vaillant thermostat

### ISSUE THREAD

**Issue by tojeroman** [MislavMandaric/home-assistant-vaillant-vsmart#251]
In the past I used the https://github.com/pjmaenh/home-assistant-vaillant integration and had the option to preset: Increase hot water consumption on my Vaillant thermostat (rebrand netatmo thermostat). I switched the integration to yours today and I'm missing that option here. Is it possible to supplement it? Thank you

**Comment by MislavMandaric** [comment]
This feature exists as part of the water heater entity, as operation `hot_water_boost`.
