### ISSUE TITLE
Migo_link support

### ISSUE THREAD

**Issue by andreaconsadori** [MislavMandaric/home-assistant-vaillant-vsmart#260]
Hello, i've a Migo link gateway and i dont undestand if supported in this integration since i ready about valliant and migo (never see migo link),
Also in case of migolink i Need to extract Always the auth code from valliant apk or migo apk? In migolink apk i cannot found any auth code.

Thanks for the reply

**Comment by andreaconsadori** [comment]
Actuallt i can only configure as Migo Link Home Kit controller but it only expose thermostat temperature and i want to see the gas and electricity used (exposed in migolink app)

**Comment by Rafapadilla93** [comment]
Hello, Have you found a way to get the Secret Key out of the MigoLink app?

I need help with this... Thank you!

**Comment by MislavMandaric** [comment]
Please use [community thread](https://community.home-assistant.io/t/added-support-for-vaillant-thermostat-how-to-integrate-in-official-release/31858) to check from others if the integration can be used with Migo Link.
