### ISSUE TITLE
Add extra sensors for gas consumption?

### ISSUE THREAD

**Issue by Seliaks65** [MislavMandaric/home-assistant-vaillant-vsmart#264]
I only just discovered in my vSmart app that on the information page of the app I can now see the gas consumption of my boiler - this appears to be a new feature of the April 2023 update of the app/Firmware 14 perhaps.

It would be really great if you could add two sensors to the entities in the integration which reports the gas consumption. The app appears to report consumption at 30 minute intervals and for my system, which is a system boiler with a hot water cylinder, it splits the reported data into Heating and Hot Water - so a sensor for each value would be great. I guess that this data may not be available from all Vaillant boilers - mine's a 2015 Ecotec Plus 624 in the UK. The app also reports the boiler's electricity use, which may be of interest for some users, although I'm not that bothered about it as it seems very low.

Thank you!

Screenshots from the app for info:

![Heating graph and data](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/assets/122552991/ec4f609e-c0df-4a59-9b10-e5802c26936f)
![HW graph and data](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/assets/122552991/49585964-f42a-4d13-8c97-7ae3b7cfbdc6)

**Comment by albaintor** [comment]
Same request here. I can help for the integration if the data is available

**Comment by albaintor** [comment]
I see that you’re integration is based on websockets. I guess this is another event to subscribe to and then linked to a new sensor. I will dig this around

**Comment by albaintor** [comment]
I nailed it but it won't get retrieved through websocket (maybe it is possible) but through API.
I will pull a request soon

**Comment by albaintor** [comment]
I have just pushed the request, here is the result :

<img width="247" alt="image" src="https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/assets/118518828/fd765742-fd06-409d-adb5-905f0e42969b">

**Comment by Muriel2Horak** [comment]
Great work @albaintor . Many thanks 

<img width="343" alt="image" src="https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/assets/137921218/57cc26e5-8b56-4650-9cbb-2163405a0128">

**Comment by albaintor** [comment]
Hi again,

I have to check after something : the consumption does not seem to increase every 5 minutes as expected, just right after HA start.
Stay tuned...

**Comment by albaintor** [comment]
It should be fixed now, I am waiting for the next update with gaz consumption...

**Comment by apilone** [comment]
Hi. I’m quite new with home assistant. 
How to install this new feature of the integration? 
I’m currently running on v 0.9.0
Thx

**Comment by albaintor** [comment]
Hi,
as there is no news from the creator, I have published a release on my fork :
https://github.com/albaintor/home-assistant-vaillant-vsmart/releases/tag/v1.0.0
Unzip it and copy home-assistant-vaillant-vsmart-1.0.0/custom_components/vaillant_vsmart folder content to your Home assistant instance in the following folder : config/custom_components/vaillant_vsmart
Then restart your Home assistant instance and you should see the new sensors

Also I have added them to the energy dashboard with a kwh cost so that I can follow how much it costs at anytime with history

**Comment by apilone** [comment]
@albaintor I went throught your instruction. I got below error message restarting HA. What I did wrong?
thx

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 22:10:02 (1 occurrences)
Last logged: 22:10:02

Setup failed for custom integration 'vaillant_vsmart': Unable to import component: No module named 'custom_components.vaillant_vsmart_0'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.vaillant_vsmart_0'

**Comment by apilone** [comment]
@albaintor reverting back to previous version 0.9.0 HA restarted without issues

**Comment by albaintor** [comment]
Mmm… are you sure you replaced the files correctly ?
Because your traces mention « vaillant_vsmart_0 «  subfolder

**Comment by apilone** [comment]
any idea on the reason why Gaz sensors even if visible under Vaillant Device appear as undefined in both "Developper Tools>>Templates" and Helpers>>Template Sensor?
![image](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/assets/17906993/24c7e258-21d4-439d-9fc9-2a2447a8f9bc)

**Comment by apilone** [comment]
Got it. I forgot to include the sensor name in " "

**Comment by apilone** [comment]
Hi, any option to retrieve, in addition to Gas and Electricity consumption,
1- Vaillant % working time
2- Temperature
both are visible vSmart information graph
![IMG_2782](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/assets/17906993/68f848a5-b9fc-4cae-bc30-1c8e6ec1b234)

**Comment by MislavMandaric** [comment]
This is now implemented as part of the new dev pre-release v0.10.0-dev.1, which I'll publish as final release in couple of days.

Feel free to update and test it out. As already written in #210, big thanks to @albaintor for the initial implementation of these sensors!

**Comment by vobelic** [comment]
Which firmware version are you guys using? 
I have the thermostat firmware 14 and gateway firmware 1030, but in the "Vaillant vSMART Control" (aka eRELAX/vSMART) app version 2.4.3.0 I don't seem to have the gas/electric consumption shown through the info - only the "Boiler operations" appears.

In HA with HACS integration version 0.10.0 I also see the energy_gas_heating and energy_gas_hot_water sensors but readings are all 0.
Am I to assume that my boiler doesn't supply those values over eBUS towards the vsmart gateway?
