### ISSUE TITLE
Warm water boost

### ISSUE THREAD

**Issue by MarcDunon** [MislavMandaric/home-assistant-vaillant-vsmart#274]
Hi

How can we now put warmwater boost in google home as entity ?

Before the update : in yaml file :

exposed_domains:
  -switch
entity_config:
  switch.thermostaat_hwb:
   expose: true

  climate.thermostaat:
   expose: true

What now ?

Thanks

Marc

**Comment by MislavMandaric** [comment]
With the new v.0.10.0 version, the HWB switch is back and it can be exposed to Google Home same as before.
