### ISSUE TITLE
Can't start the boiler through the automatisation

### ISSUE THREAD

**Issue by impactcsgo** [MislavMandaric/home-assistant-vaillant-vsmart#316]
Hi everyone, 

I can set the boiler off with this command:

device_id: c2b7285bfcc168deb839ffd52dd08f0b
domain: climate
entity_id: 347309ae6c1fef1a5332063efdb1d914
type: set_hvac_mode
hvac_mode: "off"

But in home assistant there is no existing line for => hvac_mode: "on"
I can use between "auto, heat or off"
When I select auto or heat nothing happens, so how do I get it to start again ?

Thanks

**Comment by MislavMandaric** [comment]
With the change in 0.9.0, there is no `off` mode for the climate entity. To turn the boiler off, you have to set the water heater entity operation mode to `stand_by`.
