### ISSUE TITLE
hass.components.websocket_api deprecated - Stop working in HASS 2024.9

### ISSUE THREAD

**Issue by arkixana** [MislavMandaric/home-assistant-vaillant-vsmart#335]
## Debug log

Registrador: homeassistant.helpers.frame
Fuente: helpers/frame.py:188
Ocurrió por primera vez: 19:42:51 (2 ocurrencias)
Último inicio de sesión: 19:42:55

Detected that custom integration 'vaillant_vsmart' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/vaillant_vsmart/websockets.py, line 118: hass.components.websocket_api.async_register_command(websocket_get_schedules), please create a bug report at https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/issues

**Comment by anthonyjhicks** [comment]
Another vote for this one - noticed the deprecation warning in my logs too.  Does someone want to have a go at contributing a fix for this?

**Comment by attilaersek** [comment]
I've submitted a fix to the deprecations announced here: https://developers.home-assistant.io/blog/2024/02/27/deprecate-bind-hass-and-hass-components

However, I'm not a python engineer... at all... so please test it carefully and feel free to leave comments and change requests.

**Comment by attilaersek** [comment]
@MislavMandaric could you please have a look on the PR?
